### Package To Read The Dataset 

In [1]:
import pandas as pd

### Reading The Dataset

In [2]:
data=pd.read_csv('Churn_Modelling.csv')
data

RowNumber  CustomerId    Surname  CreditScore Geography  Gender   Age  \
0             1    15634602   Hargrave          619    France  Female  42.0   
1             2    15647311       Hill          225       NaN  Female  41.0   
2             3    15619304       Onio          629    France  Female  42.0   
3             4    15701354       Boni          699    France  Female  39.0   
4             5    15737888   Mitchell          850     Spain  Female  43.0   
...         ...         ...        ...          ...       ...     ...   ...   
9995       9996    15606229   Obijiaku          771    France    Male  39.0   
9996       9997    15569892  Johnstone          516    France    Male  35.0   
9997       9998    15584532        Liu          709    France  Female  36.0   
9998       9999    15682355  Sabbatini          772   Germany    Male  42.0   
9999      10000    15628319     Walker          792    France  Female  28.0   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

### Checking For Null Values

In [3]:
data.isnull().any()

RowNumber          False
CustomerId         False
Surname            False
CreditScore        False
Geography           True
Gender              True
Age                 True
Tenure             False
Balance            False
NumOfProducts      False
HasCrCard          False
IsActiveMember     False
EstimatedSalary    False
Exited             False
dtype: bool

### Counting The Null Values

In [4]:
data.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          1
Gender             1
Age                1
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

### Filling The Null Values

In [5]:
data['Geography'].fillna(data['Geography'].mode()[0],inplace=True)
data['Gender'].fillna(data['Gender'].mode()[0],inplace=True)
data['Age'].fillna(data['Age'].mean(),inplace=True)

In [6]:
data.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [7]:
data

RowNumber  CustomerId    Surname  CreditScore Geography  Gender   Age  \
0             1    15634602   Hargrave          619    France  Female  42.0   
1             2    15647311       Hill          225    France  Female  41.0   
2             3    15619304       Onio          629    France  Female  42.0   
3             4    15701354       Boni          699    France  Female  39.0   
4             5    15737888   Mitchell          850     Spain  Female  43.0   
...         ...         ...        ...          ...       ...     ...   ...   
9995       9996    15606229   Obijiaku          771    France    Male  39.0   
9996       9997    15569892  Johnstone          516    France    Male  35.0   
9997       9998    15584532        Liu          709    France  Female  36.0   
9998       9999    15682355  Sabbatini          772   Germany    Male  42.0   
9999      10000    15628319     Walker          792    France  Female  28.0   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

### Seperating Dependent and Independent Variable

In [8]:
x=data.iloc[:,3:13].values
y=data.iloc[:,-1].values

In [9]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [225, 'France', 'Female', ..., 0, 1, 112542.58],
       [629, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [10]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

### To Know The Different Type Of Values Available On A Particular Column

In [11]:
data['Geography'].value_counts()

France     5015
Germany    2509
Spain      2476
Name: Geography, dtype: int64

### Using OneHot Encoder and Column Transformer To Convert Characters To Numbers

In [12]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [13]:
col_trans=ColumnTransformer([('aj',OneHotEncoder(),[2])],remainder='passthrough')
x=col_trans.fit_transform(x)

In [14]:
x[0]

array([1.0, 0.0, 619, 'France', 42.0, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [15]:
col_trans=ColumnTransformer([('aj',OneHotEncoder(),[3])],remainder='passthrough')
x=col_trans.fit_transform(x)

In [16]:
x[0]

array([1.0, 0.0, 0.0, 1.0, 0.0, 619, 42.0, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

In [17]:
x[0,:]

array([1.0, 0.0, 0.0, 1.0, 0.0, 619, 42.0, 2, 0.0, 1, 1, 1, 101348.88],
      dtype=object)

### Using Standard Scalar

In [18]:
from sklearn.preprocessing import StandardScaler

In [19]:
std_sca=StandardScaler()
x=std_sca.fit_transform(x)
x

array([[ 0.99700449, -0.57873591, -0.57365519, ...,  0.64609167,
         0.97024255,  0.02188649],
       [ 0.99700449, -0.57873591, -0.57365519, ..., -1.54776799,
         0.97024255,  0.21653375],
       [ 0.99700449, -0.57873591, -0.57365519, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [ 0.99700449, -0.57873591, -0.57365519, ..., -1.54776799,
         0.97024255, -1.00864308],
       [-1.00300451,  1.72790383, -0.57365519, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [ 0.99700449, -0.57873591, -0.57365519, ...,  0.64609167,
        -1.03067011, -1.07636976]])

In [20]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

### Splitting Data's For Training and Testing Purpose

In [21]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [22]:
x_train

array([[ 0.99700449, -0.57873591, -0.57365519, ...,  0.64609167,
         0.97024255, -0.77021814],
       [ 0.99700449, -0.57873591, -0.57365519, ...,  0.64609167,
        -1.03067011, -1.39576675],
       [ 0.99700449, -0.57873591, -0.57365519, ..., -1.54776799,
         0.97024255, -1.49965629],
       ...,
       [ 0.99700449, -0.57873591, -0.57365519, ...,  0.64609167,
        -1.03067011,  1.41441489],
       [-1.00300451, -0.57873591,  1.74320745, ...,  0.64609167,
         0.97024255,  0.84614739],
       [-1.00300451,  1.72790383, -0.57365519, ...,  0.64609167,
        -1.03067011,  0.32630495]])

In [23]:
y_train

array([1, 0, 0, ..., 0, 0, 1], dtype=int64)

In [24]:
x_test

array([[-1.00300451,  1.72790383, -0.57365519, ...,  0.64609167,
         0.97024255,  1.61304597],
       [ 0.99700449, -0.57873591, -0.57365519, ...,  0.64609167,
        -1.03067011,  0.49753166],
       [-1.00300451, -0.57873591,  1.74320745, ...,  0.64609167,
         0.97024255, -0.4235611 ],
       ...,
       [ 0.99700449, -0.57873591, -0.57365519, ...,  0.64609167,
         0.97024255,  1.17045451],
       [ 0.99700449, -0.57873591, -0.57365519, ...,  0.64609167,
         0.97024255, -0.50846777],
       [-1.00300451,  1.72790383, -0.57365519, ...,  0.64609167,
         0.97024255, -1.15342685]])

In [25]:
y_test

array([0, 1, 0, ..., 0, 0, 1], dtype=int64)

### Using Standard Scalar

In [26]:
from sklearn.preprocessing import StandardScaler

In [27]:
std_sca=StandardScaler()
x_train=std_sca.fit_transform(x_train)
x_test=std_sca.fit_transform(x_test)

In [28]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

### Building The Model

### Since ANN is Sequential This is the Package Used For Building The Model

In [29]:
from keras.models import Sequential

Using TensorFlow backend.
C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py

In [30]:
model=Sequential()

### Adding Input,Hidden, and Output Layers

### Package Used For Adding the Layer To The Model

In [31]:
from keras.layers import Dense

In [32]:
row,column=x_train.shape

In [33]:
row

7000

In [34]:
column

13

### Adding Input Layer To The Model

In [35]:
model.add(Dense(units=column,init='random_uniform',activation='relu'))

C:\Users\Admin\anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=13, activation="relu", kernel_initializer="random_uniform")`
  """Entry point for launching an IPython kernel.


### Adding Hidden Layer To The Model

In [36]:
# The units for the hidden layer should be either 'no.of columns*2' or 'no.of columns/2'
model.add(Dense(units=column*2,init='random_uniform',activation='relu'))

C:\Users\Admin\anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=26, activation="relu", kernel_initializer="random_uniform")`
  


### Adding Ouput Layer To The Model

In [37]:
# Since The Output is in the form of classification we use sigmoid activation
model.add(Dense(units=1,init='random_uniform',activation='sigmoid'))

C:\Users\Admin\anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=1, activation="sigmoid", kernel_initializer="random_uniform")`
  


### Compiling the Model

In [38]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
# adam - mini batch gradient descent
# metrics - 'accuracy' for classification or categorical and 'mse' for regression 

### Training The Model

In [39]:
model.fit(x_train,y_train,epochs=300,batch_size=32)
# epochs - how many times you have to train the model
# batch_size - 32 rows in each batch
    # for each epochs 1 batch(group of 32 rows) is taken
    # for each epochs loss and accuracy is printed adjacent to it




Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

Epoch 1/300
7000/7000 [==============================] - 1s 192us/step - loss: 0.5294 - acc: 0.7946
Epoch 2/300
7000/7000 [==============================] - 0s 62us/step - loss: 0.4322 - acc: 0.7977
Epoch 3/300
7000/7000 [==============================] - 0s 46us/step - loss: 0.4258 - acc: 0.7977
Epoch 4/300
7000/7000 [==============================] - 0s 49us/step - loss: 0.4205 - acc: 0.8143
Epoch 5/300
7000/7000 [==============================] - 0s 47us/step - loss: 0.4151 - acc: 0.8256
Epoch 6/300
7000/7000 [==============================] - 0s 49us/step - loss: 0.4111 - acc: 0.8287
Epoch 7/300
7000/7000 [==============================] - 0s 53us/step - loss: 0.4068 - acc: 0.8311
Epoch 8/300
7000/7000 [==============================] - 0s 50us/step - loss: 0.4044 - acc: 0.8326
Epoch 9/300
7000/7000 [==============================] - 0s 48us/step - loss: 0.4019 - acc: 0.8333
Epoch 10/3

7000/7000 [==============================] - 0s 47us/step - loss: 0.3324 - acc: 0.8670
Epoch 73/300
7000/7000 [==============================] - 0s 45us/step - loss: 0.3304 - acc: 0.8643
Epoch 74/300
7000/7000 [==============================] - 0s 46us/step - loss: 0.3301 - acc: 0.8651
Epoch 75/300
7000/7000 [==============================] - 0s 52us/step - loss: 0.3287 - acc: 0.8669
Epoch 76/300
7000/7000 [==============================] - 0s 46us/step - loss: 0.3283 - acc: 0.8676
Epoch 77/300
7000/7000 [==============================] - 0s 57us/step - loss: 0.3279 - acc: 0.8663
Epoch 78/300
7000/7000 [==============================] - 1s 78us/step - loss: 0.3277 - acc: 0.8657
Epoch 79/300
7000/7000 [==============================] - 0s 54us/step - loss: 0.3265 - acc: 0.8674
Epoch 80/300
7000/7000 [==============================] - 0s 49us/step - loss: 0.3269 - acc: 0.8666
Epoch 81/300
7000/7000 [==============================] - 0s 55us/step - loss: 0.3256 - acc: 0.8679
Epoch 82/300


7000/7000 [==============================] - 0s 44us/step - loss: 0.3170 - acc: 0.8690
Epoch 154/300
7000/7000 [==============================] - 0s 42us/step - loss: 0.3178 - acc: 0.8679
Epoch 155/300
7000/7000 [==============================] - 0s 45us/step - loss: 0.3171 - acc: 0.8706
Epoch 156/300
7000/7000 [==============================] - 0s 42us/step - loss: 0.3174 - acc: 0.8680
Epoch 157/300
7000/7000 [==============================] - 0s 41us/step - loss: 0.3179 - acc: 0.8691
Epoch 158/300
7000/7000 [==============================] - 0s 43us/step - loss: 0.3179 - acc: 0.8690
Epoch 159/300
7000/7000 [==============================] - 0s 44us/step - loss: 0.3188 - acc: 0.8683
Epoch 160/300
7000/7000 [==============================] - 0s 71us/step - loss: 0.3176 - acc: 0.8716
Epoch 161/300
7000/7000 [==============================] - 0s 50us/step - loss: 0.3172 - acc: 0.8714
Epoch 162/300
7000/7000 [==============================] - 0s 43us/step - loss: 0.3176 - acc: 0.8689
Epoc

Epoch 234/300
7000/7000 [==============================] - 0s 43us/step - loss: 0.3147 - acc: 0.8687
Epoch 235/300
7000/7000 [==============================] - 0s 42us/step - loss: 0.3134 - acc: 0.8711
Epoch 236/300
7000/7000 [==============================] - 0s 42us/step - loss: 0.3133 - acc: 0.8699
Epoch 237/300
7000/7000 [==============================] - 0s 50us/step - loss: 0.3154 - acc: 0.8727
Epoch 238/300
7000/7000 [==============================] - 0s 53us/step - loss: 0.3146 - acc: 0.8693
Epoch 239/300
7000/7000 [==============================] - 0s 46us/step - loss: 0.3136 - acc: 0.8703
Epoch 240/300
7000/7000 [==============================] - 0s 45us/step - loss: 0.3141 - acc: 0.8716
Epoch 241/300
7000/7000 [==============================] - 0s 41us/step - loss: 0.3142 - acc: 0.8700
Epoch 242/300
7000/7000 [==============================] - 0s 42us/step - loss: 0.3146 - acc: 0.8714
Epoch 243/300
7000/7000 [==============================] - 0s 45us/step - loss: 0.3135 - ac

###  Testing The Model By Predicting The Value

In [40]:
y_pred=model.predict(x_test)
y_pred

array([[0.2543386 ],
       [0.2577759 ],
       [0.0616717 ],
       ...,
       [0.08748052],
       [0.02317113],
       [0.46956348]], dtype=float32)

In [41]:
y_test

array([0, 1, 0, ..., 0, 0, 1], dtype=int64)

### Since We Used Sigmoid Function the values will be ranging near '0' so converting it into '0' or '1' using 

In [42]:
y_pred=y_pred>0.5
# Values greater than 0.5 returns True else it returns False
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

### Predicting The Value For User's Input

In [43]:
std_use_input=std_sca.fit_transform([[1.0, 0.0, 0.0, 1.0, 0.0, 699, 39.0, 1, 0.0, 2, 0, 0, 93826.63]])
model.predict(std_use_input)

array([[0.14700516]], dtype=float32)

### Finding The Accuracy Of The Model

In [44]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8573333333333333

### Format Of Confusion Matrix

In [45]:
print("[['True Positive','False Negative'],\n['False Positive','True Negative']]")

[['True Positive','False Negative'],
['False Positive','True Negative']]


### Checking The Accuracy Using Confusion Matrix

In [46]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[2267  112]
 [ 316  305]]


### Manually calculated Accuracy

    Accuracy=(True positive+True Negative)/(True positive+True Negative+False positive+False Negative)

In [47]:
print((cm[0][0]+cm[1][1])/(cm[0][0]+cm[1][1]+cm[1][0]+cm[0][1]))

0.8573333333333333


### Calculating Accuracy Using Package

In [48]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8573333333333333